// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/18/2024, 8:41:13 PM
const configMerger = require("C:/git/codingyourcareer/ConstantReminders-UI/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/git/codingyourcareer/ConstantReminders-UI/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/git/codingyourcareer/ConstantReminders-UI/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/git/codingyourcareer/ConstantReminders-UI/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/git/codingyourcareer/ConstantReminders-UI/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/git/codingyourcareer/ConstantReminders-UI/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/git/codingyourcareer/ConstantReminders-UI/plugins/**/*.{js,ts,mjs}","C:/git/codingyourcareer/ConstantReminders-UI/composables/**/*.{js,ts,mjs}","C:/git/codingyourcareer/ConstantReminders-UI/utils/**/*.{js,ts,mjs}","C:/git/codingyourcareer/ConstantReminders-UI/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/git/codingyourcareer/ConstantReminders-UI/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/git/codingyourcareer/ConstantReminders-UI/app.config.{js,ts,mjs}"] } }));

module.exports = config
