// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/18/2024, 7:04:16 PM
const configMerger = require("C:/Users/verke/source/repos/ConstantReminders-UI/node_modules/.pnpm/@nuxtjs+tailwindcss@6.12.2_magicast@0.3.5_rollup@4.27.3_ts-node@10.9.2_@types+node@22.9.0_typescript@5.6.3_/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/Users/verke/source/repos/ConstantReminders-UI/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/verke/source/repos/ConstantReminders-UI/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/verke/source/repos/ConstantReminders-UI/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/verke/source/repos/ConstantReminders-UI/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/verke/source/repos/ConstantReminders-UI/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/verke/source/repos/ConstantReminders-UI/plugins/**/*.{js,ts,mjs}","C:/Users/verke/source/repos/ConstantReminders-UI/composables/**/*.{js,ts,mjs}","C:/Users/verke/source/repos/ConstantReminders-UI/utils/**/*.{js,ts,mjs}","C:/Users/verke/source/repos/ConstantReminders-UI/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/verke/source/repos/ConstantReminders-UI/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/verke/source/repos/ConstantReminders-UI/app.config.{js,ts,mjs}"] } }));

module.exports = config
